# Generated by Django 4.0.2 on 2022-03-06 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0005_product_how_to_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_detail',
            name='web_heading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product_how_to_use',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_how_to_use', to='product_api.product_detail'),
        ),
    ]
