# Generated by Django 4.0.2 on 2022-03-24 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0007_brandlogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandlogo',
            name='Brand_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
