# Generated by Django 4.0.2 on 2022-03-18 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_detail', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping_detail',
            name='user_id',
        ),
    ]
