# Generated by Django 4.0.2 on 2022-03-05 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_product_review_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_review',
            name='review_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
