# Generated by Django 4.0.2 on 2022-03-03 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipping_detail', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField()),
                ('payment_method', models.BooleanField()),
                ('quantity', models.PositiveIntegerField()),
                ('total_value', models.PositiveIntegerField()),
                ('states', models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Pending', max_length=10)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product_info', to='product_api.product_detail')),
                ('shipping_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_shipping_info', to='shipping_detail.shipping_detail')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_user_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
