# Generated by Django 4.0.2 on 2022-03-03 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_detail',
            name='states',
        ),
    ]
