# Generated by Django 4.0.2 on 2022-03-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_detail_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detail',
            name='order_states',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Pending', max_length=10, null=True),
        ),
    ]
