# Generated by Django 4.0.2 on 2022-03-11 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_detail_order_states'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_detail',
            name='user_id',
        ),
    ]
