# Generated by Django 4.0.2 on 2022-03-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_detail_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detail',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
