# Generated by Django 4.0.2 on 2022-03-24 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_detail_razorpay_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail',
            name='order_states',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Returned', 'Returned')], default='Pending', max_length=10, null=True),
        ),
    ]
