# Generated by Django 4.0.2 on 2022-03-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_detail_order_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detail',
            name='product_awb_no',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
